name: "Loadtest"

# any branch is useful for testing before a PR is submitted
on: [push, pull_request]

permissions:
  contents: read

jobs:
  withoutplugins:
    # run on pushes to any branch
    # run on PRs from external forks
    if: |
      (github.event_name != 'pull_request')
      || (github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id)
    name: without plugins
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            src/package-lock.json
            src/bin/doc/package-lock.json
      -
        name: Install all dependencies and symlink for ep_etherpad-lite
        run: src/bin/installDeps.sh
      -
        name: Install etherpad-load-test
        run: sudo npm install -g etherpad-load-test
      -
        name: Run load test
        run: src/tests/frontend/travis/runnerLoadTest.sh 25 50

  withplugins:
    # run on pushes to any branch
    # run on PRs from external forks
    if: |
      (github.event_name != 'pull_request')
      || (github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id)
    name: with Plugins
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            src/package-lock.json
            src/bin/doc/package-lock.json
      -
        name: Install all dependencies and symlink for ep_etherpad-lite
        run: src/bin/installDeps.sh
      -
        name: Install etherpad-load-test
        run: sudo npm install -g etherpad-load-test
      -
        name: Install etherpad plugins
        run: >
          npm install
          ep_align
          ep_author_hover
          ep_cursortrace
          ep_font_size
          ep_hash_auth
          ep_headings2
          ep_markdown
          ep_readonly_guest
          ep_set_title_on_pad
          ep_spellcheck
          ep_subscript_and_superscript
          ep_table_of_contents
      -
        name: Run load test
        run: src/tests/frontend/travis/runnerLoadTest.sh 25 50

  long:
    # run on pushes to any branch
    # run on PRs from external forks
    if: |
      (github.event_name != 'pull_request')
      || (github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id)
    name: long running
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            src/package-lock.json
            src/bin/doc/package-lock.json
      -
        name: Install all dependencies and symlink for ep_etherpad-lite
        run: src/bin/installDeps.sh
      -
        name: Install etherpad-load-test
        run: sudo npm install -g etherpad-load-test
      -
        name: Run load test
        run: src/tests/frontend/travis/runnerLoadTest.sh 5000 5
